### ISSUE TITLE
coding standard?

### ISSUE THREAD

**Issue by jrobeson** [sidorares/dbus-native#103]
What is the coding standard for this project? I see some if's that have braces and some that don't. and some if's that are indented, and some that aren't.

**Comment by sidorares** [comment]
I'm using two spaces now, I'd like to convert old code to use this

**Comment by sidorares** [comment]
would be good to add eslint config ( and have it in tests ) and enforce some standard
which one you prefer? https://github.com/sidorares/node-mysql2 is using more or less consistent standard

**Comment by jrobeson** [comment]
I have no preference.

**Comment by sidorares** [comment]
btw happy to add you as collaborator if you wish

**Comment by jrobeson** [comment]
Since we were talking about node version support in another bug, I should mention that neither eslint nor jslint test against 0.8x anymore.

**Comment by sidorares** [comment]
you mean recent versions of eslint unable to run under 0.8 runtime or they unable to lint code intended for 0.8? If first easiest way is not to lint for pre 0.10 in CI matrix ( lint error would be visible anyway in other tests )

**Comment by jrobeson** [comment]
I meant that they don't test to make sure it works properly under 0.8.x.. whether it actually does, I'm not sure. It's not explicitly set to require  node > 0.10 in `engines` in the package.json file, but it's not included at all in their test matrix either.

**Comment by jrobeson** [comment]
Oh, i got confused on jslint vs jshint! jshint is the one I meant.  jslint is old.

**Comment by YurySolovyov** [comment]
Is this still relevant?

@sidorares what is your preferred targeting of this module?
Given that 0.8, 0.10, and 0.12 are either EOL or close to it, maybe it is ok to target 4.x LTS?

If not, I'd still done one-off eslint pass with `eslint:recommended` preset.

**Comment by sidorares** [comment]
yes, still relevant. happy to drop 0.8, 0.10, and 0.12 support (at least in tests)

**Comment by YurySolovyov** [comment]
I can do a PR with fixing it and adding eslint. Do you have time to review it?

**Comment by sidorares** [comment]
yes, please do. Maybe borrow config from node-mysql2: https://github.com/sidorares/node-mysql2/blob/master/.eslintrc

**Comment by jrobeson** [comment]
I guess we can close this one too since we *finally* adopted eslint and prettier in #182
