### ISSUE TITLE
buffer is undefined in  writeSimple

### ISSUE THREAD

**Issue by lamazavr** [sidorares/dbus-native#111]
Hi, I have trubles with writeSimple function in lib/marshall.js 
Here is a problem line:

`if (Buffer.isBuffer(data)) data = buffer.toString(); // encoding?`

This problem causes a crash on writing with appropriate type.

**Comment by sidorares** [comment]
(this is the line you talking about ) 
https://github.com/sidorares/node-dbus/blob/a729710ea01db4dbb44bd6cafa7c8925c3724a09/lib/marshall.js#L104

could you post your error and stack trace?

**Comment by lamazavr** [comment]
Here is trace:

`/usr/lib/node_modules/dbus-native/lib/marshall.js:104
  if (Buffer.isBuffer(data)) data = buffer.toString(); // encoding?
                                    ^

ReferenceError: buffer is not defined
    at writeSimple (/usr/lib/node_modules/dbus-native/lib/marshall.js:104:37)
    at write (/usr/lib/node_modules/dbus-native/lib/marshall.js:92:14)
    at write (/usr/lib/node_modules/dbus-native/lib/marshall.js:60:7)
    at writeStruct (/usr/lib/node_modules/dbus-native/lib/marshall.js:32:5)
    at module.exports (/usr/lib/node_modules/dbus-native/lib/marshall.js:17:13)
    at Object.marshallMessage [as marshall] (/usr/lib/node_modules/dbus-native/lib/message.js:84:16)
    at EventEmitter.self.message (/usr/lib/node_modules/dbus-native/index.js:118:28)
    at bus.invoke (/usr/lib/node_modules/dbus-native/lib/bus.js:28:24)
    at set_parameter_value (/opt/snmpserv.js:50:16)
    at agent.request.handler (/opt/snmpserv.js:111:25)
`
Such error happens when I call bus.invoke() with Buffer parameter instead of integer.

**Comment by sidorares** [comment]
yes, buffer is undefined, looks like a bug

I think I meant to have something like this:
```js
  if (Buffer.isBuffer(data)) data = data.toString();
```

Do you know what is the type of parameter? In general, raw binary data should have `ay` signature ( array of unsigned bytes ).

**Comment by lamazavr** [comment]
I call invoke() from snmp handler, so the type of parameter is Buffer (when it crashes).
Do i need to check the type of incoming data?

**Comment by sidorares** [comment]
can I look at set_parameter_value function? Is it called from

https://github.com/ComEngineering/Monitoring_Software/blob/cca29b6073b12e73e74a35c11dd7fae24463ddde/olinuxino-a10-lime/meta-teko/recipes-teko/snmpserv/snmpserv/snmpserv.js

?

**Comment by lamazavr** [comment]
Here it is: https://github.com/ComEngineering/Monitoring_Software/blob/snmp_dev/olinuxino-a10-lime/meta-teko/recipes-teko/snmpserv/snmpserv/snmpserv.js#L45

**Comment by sidorares** [comment]
not exactly related, but do you know why one of the parameters is Buffer?
You call as `'iyai', [param.addr, param.reg, [value]]`, I'd expect all values to be integer numbers

**Comment by lamazavr** [comment]
It is because of the snmpjs module, it returns Buffer object when I write string value over snmp.

**Comment by jrobeson** [comment]
This was fixed in https://github.com/sidorares/dbus-native/commit/f6a1960a4312a1aabf6375438c67ea1bb860573b#diff-528e6b90dea4f34a18f288d3c8e0526a
