### ISSUE TITLE
Node 4.x minimum version?

### ISSUE THREAD

**Issue by jrobeson** [sidorares/dbus-native#187]
What's the minimum version of 4.x that we support? I see that travis has 4.5 set.

**Comment by sidorares** [comment]
node.green show same results 4.0.0 to 4.8.4, if what we have currently works with 4.0.0 would be good to support. Happy to bump requirement to 6.x with next backwards incompatible change

**Comment by jrobeson** [comment]
Buffer isn't represented on that table though is it? just the stuff that comes for free from v8 right?

https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html#buffer_class_method_buffer_from_buffer

Added in 4.5.0

**Comment by jrobeson** [comment]
It (and other buffer methods) was originally added for 8.x, but was backported

**Comment by sidorares** [comment]
we can use safe-buffer polyfill:

https://github.com/sidorares/node-mysql2/issues/380
https://github.com/sidorares/node-mysql2/pull/589

**Comment by jrobeson** [comment]
Sounds good.  Seems like the target should node 4.2 then, as that's the version in the previous Ubuntu LTS.

**Comment by sidorares** [comment]
4.2 sounds good to me

**Comment by jrobeson** [comment]
Both issues addressed in PRs #188 and #189
