### ISSUE TITLE
event-stream malicious code

### ISSUE THREAD

**Issue by fcastilloec** [sidorares/dbus-native#253]
The latest version of `dbus-native` in npm has a dependency to `flatmap-stream` which is not available anymore because of malaware see https://github.com/dominictarr/event-stream/issues/116#issue-382854428. I notice that the main branch is using a new version of `event-stream` which solves this issue.
Would it be possible to release a new version to `npm`?
Right now, this module is impossible to install, unless you have a cache version of it, and if the cache version is used, then we're running malaware.

**Comment by sidorares** [comment]
Thanks @fcastilloec , I'll publish master now

**Comment by fcastilloec** [comment]
I can't install `v0.3.0` but it's a different error this time. I'm getting 
> ENOENT: no such file or directory, chmod '.../node_modules/dbus-native/bin/dbus2js.js'

I can seee that the file is in your repo, but for some reason `npm` can't find it. I've deleted all my cache, so it's something to do with this specific version.

**Comment by sidorares** [comment]
Which os are you using?

**Comment by fcastilloec** [comment]
Ubuntu 18.04 64bit

**Comment by sidorares** [comment]
the script was not listed under package.json `files` section, added that. Hope will help. Can you try to install v0.4.0?

**Comment by fcastilloec** [comment]
v0.4.0 works! Thanks for updating!

**Comment by fcastilloec** [comment]
@sidorares just a last optional tip, it might be a good idea to delete v0.3.0 from npm since it's broken anyway and nobody will be able to install it.

**Comment by sidorares** [comment]
done
