### ISSUE TITLE
Unkown bus address Error

### ISSUE THREAD

**Issue by BelkaDev** [sidorares/dbus-native#280]
#### Issue description
Using the library throws an error.

#### Steps to reproduce the issue

```javascript
var dbus = require('dbus-native');
var bus = dbus.sessionBus();
```
#### What's the actual result?
```
Error: unknown bus address
    at createStream (/node_modules/dbus-native/index.js:22:26)
    at createConnection (/node_modules/dbus-native/index.js:76:31)
    at Object.module.exports.createClient (/node_modules/dbus-native/index.js:136:20)
```
#### Additional details / screenshot
OS: Arch
DE: KDE

**Comment by sidorares** [comment]
can you show what's in your `DBUS_SESSION_BUS_ADDRESS` environment variable @BelkaDev ?

**Comment by BelkaDev** [comment]
> can you show what's in your `DBUS_SESSION_BUS_ADDRESS` environment variable @BelkaDev ?

It was empty and I had to export it manually
This did the trick:
```bash
echo "export $(dbus-launch | head -n1)" >> .zshrc
```
