### ISSUE TITLE
How to get the mount-point of a plugged in usb device?

### ISSUE THREAD

**Issue by chrs1885** [sidorares/dbus-native#8]
First of all: Thank you so much for providing the dbus module for node.js. It's definitly what I was searching for! I also found one of your examples, which detects, if a usb device has been plugged in.

What I have so far:

``` javascript
var dbus = require('dbus-native');

var bus = dbus.systemBus();
udservice = bus.getService('org.freedesktop.UDisks');
udservice.getInterface(
    '/org/freedesktop/UDisks',
    'org.freedesktop.UDisks', 
    function(err, ud) {
        ud.on('DeviceAdded', function(deviceObjectPath) {
                console.log('DeviceAdded', deviceObjectPath);
        });
        ud.on('DeviceRemoved', function(deviceObjectPath) {
                console.log('DeviceRemoved', deviceObjectPath);
        });
        }
);
```

Now I'm looking for a way to get the mounting point (or name) of the device. Right now I'm getting the device object path.
Is this possible?

**Comment by fastworks** [comment]
This is a very old thread and I've been affected by the same issue. Ultimately it turns out the problem is udisks has been removed from newer versions in favour of udisks2 which has a slightly different interface. If I manage to solve the issue, I'll post it up here for future searchers.
