### ISSUE TITLE
Can not find node_modules

### ISSUE THREAD

**Issue by wpp2014** [sidorares/dbus-native#93]
I created a system bus by dbus-native, but a error occurred when I connected this service and I have set the NODE_PATH that value is /usr/lib/node_modules:/usr/local/lib/node_modules

**Comment by sidorares** [comment]
sorry, but looks like it's a problem in the way you use the library. Could you post more details?

**Comment by wpp2014** [comment]
This is service.js:
```
#!/usr/bin/env node

var dbus = require('dbus-native');

var bus = dbus.systemBus();
var name = 'org.example';

bus.requestName(name, 0);

var exampleInterface = {
	name: 'org.example',
	methods: {
		print: ['s', 's']
	}
};

var example = {
	print: function(s) {
		console.log(s);
		return s;
	}
};

bus.exportInterface(example, '/org/example', exampleInterface);
```

This is .conf file
```
<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy context="default">
    <!-- Anyone can start this service -->
    <allow own="org.example"/>

    <!-- Anyone can invoke methods-->
    <allow send_destination="org.example"/>
  </policy>
</busconfig>
```

This is .service file
```
[D-BUS Service]
Name=org.example
Exec=/usr/libexec/service.js
User=root
```

This is client.js
```
#!/usr/bin/env node

var dbus = require('dbus-native');

var systemBus = dbus.systemBus();

systemBus.getService('org.example').getInterface('/org/example', 'org.example', function(err, example) {
	if(err) {
		throw err;
	} else {
		example.print('Hello World');
	}
});
```
I copid these files to the corresponding directory and run client.js in terminal, but error occured.

**Comment by sidorares** [comment]
did you `npm install dbus-native` where your client and service is located?

**Comment by wpp2014** [comment]
/usr/local/lib/node_modules

**Comment by sidorares** [comment]
do you have dbus-native under `/usr/local/lib/node_modules` ?

**Comment by wpp2014** [comment]
yes. If I run service.js in another terminal, the result is right. The error has occured if I run client.js only.

**Comment by sidorares** [comment]
could you post full stack trace from client.js?

**Comment by wpp2014** [comment]
I tried to print env in service.js and found there is no NODE_PATH.
```
#!/usr/bin/env node

var fs = require('fs');
var execFile = require('child_process').execFile;

var out = execFile('env');
out.stdout.on('data', function(data) {
	fs.writeFileSync('/tmp/out', data);
});

/*
var dbus = require('dbus-native');

var bus = dbus.systemBus();
var name = 'org.example';

bus.requestName(name, 0);

var exampleInterface = {
	name: 'org.example',
	methods: {
		print: ['s', 's']
	}
};

var example = {
	print: function(s) {
		console.log(s);
		return s;
	}
};

bus.exportInterface(example, '/org/example', exampleInterface);
*/
```
The result is 
![1](https://cloud.githubusercontent.com/assets/7447933/9457257/686dbc32-4b13-11e5-8487-16bf7a148146.png)

**Comment by sidorares** [comment]
I actually prefer to use local modules, add package.json and run `npm install --save dbus-native` ( you can use `npm init` to generate ampty package.json _

**Comment by wpp2014** [comment]
Yes, If use absolute path there is no problem. Thank you.

**Comment by jrobeson** [comment]
Is there anything more to do here? I'm a bit confused.

**Comment by sidorares** [comment]
hey @wpp2014 hope that was solved, if not please feel free to reopen and provide additional information
